import { presetVisual, VISUAL_KEYS } from "../weather/WeatherPresets";

const clamp=(n)=>Math.max(0,Math.min(1,n)); const smooth=(t)=>{t=clamp(t);return t*t*(3-2*t);};
export class WeatherDirector {
  constructor({ atmosphere, lighting, particles, scene }) { this.atmosphere=atmosphere;this.lighting=lighting;this.particles=particles;this.scene=scene;this.current={...presetVisual("CLEAR")};this.from={...this.current};this.target={...this.current};this.weather=null;this.key="";this.started=0;this.duration=1;this.nextLightning=0;this.flash=0; }
  transitionTo(weather,{duration=4000}={}) { const key=JSON.stringify([weather?.preset,weather?.condition,weather?.cloudCoverage,weather?.precipitationRate,weather?.isDay]);if(key===this.key)return;this.key=key;this.weather=weather;Object.assign(this.from,this.current);Object.assign(this.target,presetVisual(weather?.preset||"CLEAR"));if(weather?.cloudCoverage!=null)this.target.clouds=clamp(weather.cloudCoverage/100);if(weather?.precipitationRate>0)this.target.rain=Math.max(this.target.rain,clamp(weather.precipitationRate/8));if(weather?.windSpeed>0)this.target.wind=Math.max(this.target.wind,clamp(weather.windSpeed/20));this.started=performance.now();this.duration=duration; }
  update(now,progress=1) { const t=smooth((now-this.started)/this.duration);for(const k of VISUAL_KEYS)this.current[k]=this.from[k]+(this.target[k]-this.from[k])*t;const p=clamp(progress);const atmosphere=smooth(p/.42),distant=smooth((p-.18)/.46),near=smooth((p-.58)/.38);const out={...this.current,weather:this.weather,phase:p<.3?"approach":p<.62?"descent":p<.98?"entry":"ambient"};out.clouds*=atmosphere;out.fog*=atmosphere;out.haze*=atmosphere;out.darkness*=atmosphere;out.distantPrecipitation=out.distantRain*distant;out.nearPrecipitation=out.rain*near;out.hail*=near;out.wetness*=near;out.lightning*=distant;
    if(out.lightning>.12&&now>this.nextLightning){this.flash=1;this.nextLightning=now+(6500+Math.random()*7000)/Math.max(.35,out.lightning);}this.flash*=.82;this.atmosphere.update(out);this.lighting.update({...out,lightning:this.flash});this.particles.update(out);return out; }
}
